"""Stripped down config to be used by scripts that don't intend to run the app."""
import os
import config.config as c
RUN_TASKS_ON_STARTUP = False
SCHEDULER_API_ENABLED = False
DEBUG = False
basedir = os.path.abspath(os.path.dirname(__file__))
SQLALCHEMY_MIGRATE_REPO = c.SQLALCHEMY_MIGRATE_REPO
SQLALCHEMY_TRACK_MODIFICATIONS = c.SQLALCHEMY_TRACK_MODIFICATIONS
try:
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
except KeyError:
    SQLALCHEMY_DATABASE_URI = c.SQLALCHEMY_DATABASE_URI
STEAMWOKSHOP_ITEM_URL = c.STEAMWORKSHOP_ITEM_URL
STEAMPLAYER_PROFILE_URL = c.STEAMPLAYER_PROFILE_URL
LOG_INFO_FILENAME = c.LOG_INFO_FILENAME
LOG_DEBUG_FILENAME = c.LOG_DEBUG_FILENAME
